apiVersion: apps/v1
kind: Deployment
metadata:
  name: explo-web-deployment
  labels:
    app: explo-static-site
spec:
  # Maintain 3 replicas for high availability on Flux
  replicas: 3
  selector:
    matchLabels:
      app: explo-static-site
  template:
    metadata:
      labels:
        app: explo-static-site
    spec:
      containers:
      - name: web-container
        # Using version v3 to enable the Node.js server and Telegram notifications
        image: greenlanterna/explo-site:v17
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
