apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: explo-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: explo-v1.runonflux.io  # Puoi cambiare questo nome con quello che preferisci
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: explo-web-service
            port:
              number: 80